// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"app/app"
	"app/app/controller"
	"app/app/service/impl"
	"app/infra"
	"app/infra/messages"
)

// Injectors from wire.go:

func InitApp() (*app.App, error) {
	smtpEmail := messages.NewSmtpEmailNoreply()
	baseCtl := controller.BaseCtl{
		EmailSrv: smtpEmail,
	}
	cache := infra.NewCache()
	idGenerator := infra.NewIdGenerator()
	userService := &impl.UserService{
		Email: smtpEmail,
		Cache: cache,
		Idg:   idGenerator,
	}
	userCtl := controller.UserCtl{
		UserSrv: userService,
	}
	appApp := &app.App{
		BaseCtl: baseCtl,
		UserCtl: userCtl,
	}
	return appApp, nil
}
