// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wires

import (
	"app/app/controller"
	"app/infra"
	"app/infra/messages"
)

// Injectors from wire.go:

func InitApp() (*infra.App, error) {
	smtpEmail := messages.NewSmtpEmailNoreply()
	baseCtl := &controller.BaseCtl{
		EmailSrv: smtpEmail,
	}
	app := infra.NewApp(baseCtl)
	return app, nil
}
