version: "3.1"
services:
  mysql:
    image: mysql
    container_name: user-center
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_center
      MYSQL_USER: uu
      MYSQL_PASSWORD: user-center
      TZ: Asia/Shanghai # 设置容器的默认时区
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql_data:/var/lib/mysql

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: user_center
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
