server:
  addr: ":8000"

mysql:
  base:
    service: base
    database: mall_goods
    #addr: "cetus-mall-svc.mysql:3306"
    addr: "10.112.37.50:6060"
    user: "homework"
    password: "homework"
    maxidleconns: 50
    maxopenconns: 100
    connMaxLifeTime: 3600s
    connTimeOut: 1500ms
    writeTimeOut: 3s
    readTimeOut: 3s
