server:
  addr: ":8000"

mysql:
  base:
    service: common
    database: ad

    #addr: "cetus-mall-svc.mysql:3306"
    addr: "localhost:3306"
    user: "root"
    password: "123456"
    maxidleconns: 50
    maxopenconns: 100
    connMaxLifeTime: 3600s
    connTimeOut: 1500ms
    writeTimeOut: 3s
    readTimeOut: 3s
emailNoreply:
  emailServer: "smtp.163.com"
  emailUser: "go_skeleton@163.com"
  emailPassword: "MFZNIPMCGVLAVUUE"
  emailPort: 25
